version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard_v2
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - zerologlint
  settings:
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    nestif:
      min-complexity: 6
    predeclared:
      ignore:
        - len
        - " min"
        - " max"
      qualified-name: true
    revive:
      enable-all-rules: true
      rules:
      - name: add-constant
        disabled: true
      - name: enforce-switch-style
        disabled: true
      - name: unchecked-type-assertion
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: import-shadowing
        disabled: true
      # - name: package-naming
      #   disable: true
      - name: line-length-limit
        arguments:
          - 120
    staticcheck:
      checks:
        - all
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
        use-field-name: false
    varnamelen:
      ignore-names:
        - ok
        - ip
        - "no"
        - id
        - tt
        - i
        - j
        - il
        - r
        - w
        - db
        - tx
        - wg
    ireturn:
      allow: [anon, error, empty, stdlib, generic]
  exclusions:
    generated: lax
    rules:
      - path: util/
        text: "don't use \"util\" because it is a bad package name"
